/* tslint:disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    categories: Category;
    articles: Article;
    Projects: Project;
    media: Media;
  };
  globals: {};
}
export interface User {
  id: string;
  roles?: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Category {
  id: string;
  title?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Article {
  id: string;
  title: string;
  description: string;
  category: string | Category;
  createdAt: string;
  updatedAt: string;
  type: 'blog' | 'snippet';
  content: {
    [k: string]: unknown;
  }[];
  tags: (
    | 'html'
    | 'css'
    | 'dom'
    | 'git'
    | 'github'
    | 'bash'
    | 'webpack'
    | 'seo'
    | 'typescript'
    | 'tutorial'
    | 'testing'
    | 'sql'
    | 'snippets'
    | 'security'
    | 'react'
    | 'linux'
    | 'node'
    | 'javascript'
    | 'design'
    | 'authentication'
    | 'api'
  )[];
}
export interface Project {
  id: string;
  title?: string;
  slug: string;
  createdAt: string;
  updatedAt: string;
  tagline: string;
  url: string;
  banner_img: string;
  slider?: {
    title?: string;
    image: string | Media;
    caption?: string;
    id?: string;
  }[];
  github_url: string;
  highlight: 'show' | 'hide';
}
export interface Media {
  id: string;
  alt?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    card?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    tablet?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
